web:
  image: adtd/web:stage
  ports:
    - "80"
  links:
    - rest:rest-demo-azure.marathon.mesos
rest:
  image: adtd/rest:stage
  ports:
    - "8080:8080"
lb:
  image: eeacms/haproxy
  ports:
    - "80:80"
    - "1936:1936"
  links:
    - web


